definitions:
  errcode.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  model.Blog:
    properties:
      content:
        type: string
      created_at:
        type: number
      id:
        type: integer
      name:
        type: string
      summary:
        type: string
      user_id:
        type: string
      user_image:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: blog1.0
  termsOfService: "no"
  title: 博客系统
  version: "1.0"
paths:
  /api/v1/blog:
    get:
      parameters:
      - description: 文章标题
        in: query
        maxLength: 100
        name: name
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Blog'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个标签
swagger: "2.0"
